### PR TITLE
Update for 2.9

### PR DESCRIPTION
**Pull request by Eeems**
Fix #18 
Fix https://github.com/ddvk/remarkable2-framebuffer/issues/68

### CODE REVIEW

**Comment by Eeems** [comment]
Untested as I don't have a rM2, or the 2.9 update.

**Comment by juanfcocontreras** [comment]
I get the following error:

```
./scripts/ko.sh: line 11: `kill-server': not a valid identifier
```

By making the changes that @matteodelabre has commented and leaving the script like this, it seems to work without problems: 

```
#!/bin/sh

if [ -z "$NO_XO" ]; then
    systemctl stop xochitl
fi

if [ ! -z "`pidof rm2fb-server`"]; then
    killall rm2fb-server
fi

LD_PRELOAD=/home/root/librm2fb_server.so.1.0.1 /usr/bin/xochitl &
sleep 2

export KO_DONT_SET_DEPTH=1
export KO_DONT_GRAB_INPUT=1
export LD_PRELOAD=/home/root/librm2fb_client.so.1.0.1

/home/root/apps/koreader/koreader.sh

killall rm2fb-server
systemctl reset-failed xochitl
if [ -z "$NO_XO" ]; then
    systemctl start xochitl
fi
```

**Comment by Eeems** [comment]
> I get the following error:
> 
> ```
> ./scripts/ko.sh: line 11: `kill-server': not a valid identifier
> ```

Ah right, it's running sh not bash. Try the updated version.

**Comment by Eeems** [comment]
Oh I see, rm2fb-server renames the process that's running so it should be simple enough to use the other thing. I'll switch to that.

**Comment by juanfcocontreras** [comment]
> > I get the following error:
> > ```
> > ./scripts/ko.sh: line 11: `kill-server': not a valid identifier
> > ```
> 
> Ah right, it's running sh not bash. Try the updated version.

This version is working without any issue!

**Comment by juanfcocontreras** [comment]
> Oh I see, rm2fb-server renames the process that's running so it should be simple enough to use the other thing. I'll switch to that.

Great! Thanks a lot for your interest and work!

**Pull request merged**
